# Generated by Django 3.0.1 on 2020-01-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
    ]
