# Generated by Django 3.0.1 on 2020-01-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200117_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Parent',
        ),
    ]
