# Generated by Django 3.0.1 on 2020-01-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200118_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='massage',
            field=models.TextField(verbose_name='Massage'),
        ),
    ]
