# Generated by Django 3.0.1 on 2020-01-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200118_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='massage',
            field=models.TextField(verbose_name='massage'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='pages.Detail'),
        ),
    ]
