# Generated by Django 3.0.1 on 2020-01-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20200130_2024'),
        ('cart', '0002_auto_20200130_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(to='pages.Detail'),
        ),
    ]
