# Generated by Django 3.0.1 on 2020-01-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='update',
        ),
    ]
