# Generated by Django 3.0.1 on 2020-01-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20200130_2024'),
        ('cart', '0004_auto_20200130_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Detail',
            field=models.ManyToManyField(null=True, to='pages.Detail'),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
